name: Check the code

on: [push, pull_request]

jobs:
  preprocess:
    name: Preprocess and check the code

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.3.4"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install LuaFileSystem
        run: luarocks install luafilesystem

      - name: Generate preprocessed debug and release modules
        run: lua preprocess.lua

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck release --config .luacheckrc -t